exports.NEW_CLIENT = "NEW_CLIENT";
exports.NEW_MESSAGE = "NEW_MESSAGE";
exports.NEW_SUBJECT = "NEW_SUBJECT";
exports.NEW_GIF = "NEW_GIF";
exports.CONNECTION_SUCCESS = "CONNECTION_SUCCESS";
exports.CONNECTION_ERROR_ALREADY_CONNECTED =
  "CONNECTION_ERROR_ALREADY_CONNECTED";
